In [1]:
from bonXAI.core.data_loader import DataLoader
from bonXAI.core.utils import set_global_seed
from bonXAI.core.utils import CC18_ALL, CTR23_ALL

In [21]:
data_loader = DataLoader()
dataset_name, X_train, y_train, X_test, y_test, model, preprocessor = data_loader.load_from_openml(
    dataset_id=CC18_ALL[0], 
    model_name="ann", 
)

Early stopping at epoch 75


In [22]:
from bonXAI.core.explainer import Explainer
exp = Explainer(model=model, explainer_name="shapiq", task_type="regression", seed=2)
x1 = exp.explain(X_foreground=X_test[:10], X_background=X_test[:1000], y_foreground=y_test[:10], y_background=y_test[:1000], n_jobs=10)

Explaining with ShapIQ. 10 samples to explain using 1000 background samples.


In [23]:
from bonXAI.core.explainer import Explainer
exp = Explainer(model=model, explainer_name="shapiq", task_type="regression", seed=22)
x2 = exp.explain(X_foreground=X_test[:10], X_background=X_test[:1000], y_foreground=y_test[:10], y_background=y_test[:1000], n_jobs=10)

Explaining with ShapIQ. 10 samples to explain using 1000 background samples.


In [28]:
from bonXAI.core.metrics import compute_mae

compute_mae(x1[0][0], x2[0][0])

np.float64(0.042520933035781174)

In [27]:
compute_mae(x1[0][1], x2[0][7])

np.float64(0.030522769058025898)

In [2]:
path = "expected_gradients_expected_gradients_3_ann.npz"
import numpy as np
data = np.load(path, allow_pickle=True)
data["exp_values"][0]

array([[ 2.31640195e-04, -4.06767940e-04,  2.43870265e-04, ...,
         2.88052410e-01, -2.07942754e-01, -1.17816098e-01],
       [ 2.01948758e-04,  3.08914197e-04, -4.53636894e-04, ...,
         1.09786667e-01, -1.83057338e-01, -4.65446621e-01],
       [ 2.40193418e-04, -4.93389554e-04,  1.80989387e-04, ...,
         2.34273188e-02, -3.26952428e-01, -1.14733972e-01],
       ...,
       [-5.37764265e-07, -1.65478763e-04, -4.34054265e-04, ...,
        -5.80735981e-01,  5.38769849e-02,  2.70962805e-01],
       [-1.77313271e-03, -4.59617324e-04,  8.39361688e-04, ...,
         1.18315995e-01,  2.94635028e-01, -2.18614802e-01],
       [-4.40635049e-04, -2.58753367e-04,  1.13874492e-04, ...,
         3.00262660e-01, -5.24349391e-01, -1.51751727e-01]], dtype=float32)

In [3]:
data["exp_values"][1]

array([[ 2.31889295e-04, -4.71427833e-04,  2.50794896e-04, ...,
         2.86114365e-01, -2.04279497e-01, -1.13589942e-01],
       [ 1.75267589e-04,  3.01483524e-04, -4.35741997e-04, ...,
         1.07837744e-01, -1.79333612e-01, -4.61159527e-01],
       [ 2.11648367e-04, -5.43501577e-04,  1.72410495e-04, ...,
         2.14676727e-02, -3.23211044e-01, -1.10491015e-01],
       ...,
       [-2.27376604e-05, -1.92405729e-04, -4.05599450e-04, ...,
        -5.82689226e-01,  5.75891584e-02,  2.75172859e-01],
       [-1.72135071e-03, -4.87132085e-04,  8.49196455e-04, ...,
         1.16277426e-01,  2.98270404e-01, -2.14334786e-01],
       [-4.56148235e-04, -2.39422588e-04,  9.39364763e-05, ...,
         2.98372269e-01, -5.20432591e-01, -1.47513360e-01]], dtype=float32)

In [4]:
mean = np.mean(data["exp_values"], axis=0)
mean

array([[ 2.40028836e-04, -4.41706012e-04,  2.55407358e-04, ...,
         2.86389977e-01, -2.05782816e-01, -1.16194218e-01],
       [ 1.87451093e-04,  3.05928756e-04, -4.45882528e-04, ...,
         1.08111240e-01, -1.80864498e-01, -4.63781923e-01],
       [ 2.25554089e-04, -5.22677030e-04,  1.78458475e-04, ...,
         2.17420701e-02, -3.24742585e-01, -1.13111027e-01],
       ...,
       [-1.20141085e-05, -1.82422911e-04, -4.21890611e-04, ...,
        -5.82427084e-01,  5.60635626e-02,  2.72575110e-01],
       [-1.72604376e-03, -4.70974017e-04,  8.49713164e-04, ...,
         1.16570435e-01,  2.96777248e-01, -2.16963425e-01],
       [-4.39739408e-04, -2.61521782e-04,  9.10467643e-05, ...,
         2.98647553e-01, -5.22104561e-01, -1.50168344e-01]], dtype=float32)

In [5]:
from bonXAI.core.metrics import compute_mae

compute_mae(data["exp_values"][0], mean)

np.float32(0.00039248005)