In [1]:
from bonXAI.core.data_loader import DataLoader
from bonXAI.core.utils import set_global_seed
from bonXAI.core.utils import CC18_ALL, CTR23_ALL

In [21]:
data_loader = DataLoader()
dataset_name, X_train, y_train, X_test, y_test, model, preprocessor = data_loader.load_from_openml(
    dataset_id=CC18_ALL[0], 
    model_name="ann", 
)

Early stopping at epoch 75


In [22]:
from bonXAI.core.explainer import Explainer
exp = Explainer(model=model, explainer_name="shapiq", task_type="regression", seed=2)
x1 = exp.explain(X_foreground=X_test[:10], X_background=X_test[:1000], y_foreground=y_test[:10], y_background=y_test[:1000], n_jobs=10)

Explaining with ShapIQ. 10 samples to explain using 1000 background samples.


In [23]:
from bonXAI.core.explainer import Explainer
exp = Explainer(model=model, explainer_name="shapiq", task_type="regression", seed=22)
x2 = exp.explain(X_foreground=X_test[:10], X_background=X_test[:1000], y_foreground=y_test[:10], y_background=y_test[:1000], n_jobs=10)

Explaining with ShapIQ. 10 samples to explain using 1000 background samples.


In [28]:
from bonXAI.core.metrics import compute_mae

compute_mae(x1[0][0], x2[0][0])

np.float64(0.042520933035781174)

In [27]:
compute_mae(x1[0][1], x2[0][7])

np.float64(0.030522769058025898)

In [7]:
path = "package_metadata/openml/PhishingWebsites/ground_truth/shap_kernel_3_ann.npz"
import numpy as np
data = np.load(path, allow_pickle=True)
data["exp_values"][0]

array([[ 0.02321614,  0.        ,  0.        , ...,  0.01053067,
         0.        ,  0.        ],
       [-0.05860203,  0.        ,  0.11291735, ...,  0.        ,
         0.06451205,  0.        ],
       [ 0.059746  ,  0.        ,  0.        , ...,  0.02023706,
        -0.04785993,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.01119677, ...,  0.        ,
         0.        ,  0.03874431],
       [ 0.01684088,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.03076194, ...,  0.        ,
         0.        ,  0.        ]])

In [8]:
data["exp_values"][1]

array([[ 0.01559577,  0.        ,  0.        , ...,  0.00390554,
         0.        ,  0.        ],
       [-0.05539155,  0.        ,  0.11795949, ...,  0.        ,
         0.06213241,  0.        ],
       [ 0.06181763,  0.        ,  0.        , ...,  0.01826355,
        -0.04685615,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.00289416, ...,  0.        ,
         0.        ,  0.0344726 ],
       [ 0.01385381,  0.        ,  0.        , ...,  0.        ,
         0.01326209,  0.        ],
       [ 0.        ,  0.        ,  0.02342196, ...,  0.        ,
         0.01336485,  0.        ]])

In [4]:
mean = np.mean(data["exp_values"], axis=0)
mean

array([[ 2.40028836e-04, -4.41706012e-04,  2.55407358e-04, ...,
         2.86389977e-01, -2.05782816e-01, -1.16194218e-01],
       [ 1.87451093e-04,  3.05928756e-04, -4.45882528e-04, ...,
         1.08111240e-01, -1.80864498e-01, -4.63781923e-01],
       [ 2.25554089e-04, -5.22677030e-04,  1.78458475e-04, ...,
         2.17420701e-02, -3.24742585e-01, -1.13111027e-01],
       ...,
       [-1.20141085e-05, -1.82422911e-04, -4.21890611e-04, ...,
        -5.82427084e-01,  5.60635626e-02,  2.72575110e-01],
       [-1.72604376e-03, -4.70974017e-04,  8.49713164e-04, ...,
         1.16570435e-01,  2.96777248e-01, -2.16963425e-01],
       [-4.39739408e-04, -2.61521782e-04,  9.10467643e-05, ...,
         2.98647553e-01, -5.22104561e-01, -1.50168344e-01]], dtype=float32)

In [5]:
from bonXAI.core.metrics import compute_mae

compute_mae(data["exp_values"][0], mean)

np.float32(0.00039248005)